import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import { ClerkProvider } from "@clerk/nextjs";
import BootstrapClient from "@/components/BootstrapClient";
import MyNavbar from "@/components/MyNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <MyNavbar/>
        {children}
        </body>
      <BootstrapClient/>
    </html>
    </ClerkProvider>
  );
}
